language: ruby
cache: bundler
sudo: false
bundler_args: --path vendor --local --without development
services:
  - postgresql
addons:
  postgresql: '9.6'
env:
  - DATABASE_URL="postgres://postgres@localhost/travis_ci_test"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - bin/rails db:migrate db:test:prepare
  - RUN_COVERAGE=travis bin/rails test
