---
kind: Template
apiVersion: v1
metadata:
  name: rit-class-stats
  annotations:
    openshift.io/display-name: Rails + PostgreSQL + Redis (Ephemeral)
    description: |-
      An example Rails application with a PostgreSQL database. For more information about using this template, including OpenShift considerations, see https://github.com/openshift/rails-ex/blob/master/README.md.

      WARNING: Any data stored will be lost upon pod destruction. Only use this template for testing.
    tags: quickstart,ruby,rails,redis
    iconClass: icon-ruby
    openshift.io/long-description: This template defines resources needed to develop
      a Rails application, including a build configuration, application deployment
      configuration, and database deployment configuration.  The database is stored
      in non-persistent storage, so this configuration should be used for experimental
      purposes only.
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/documentation-url: https://github.com/openshift/rails-ex
    openshift.io/support-url: https://access.redhat.com
    template.openshift.io/bindable: 'false'
message: |-
  The following service(s) have been created in your project: ${NAME}, ${DATABASE_SERVICE_NAME}.

  For more information about using this template, including OpenShift considerations, see https://github.com/openshift/rails-ex/blob/master/README.md.
labels:
  template: rit-class-stats
  app: rit-class-stats
objects:
- kind: Secret
  apiVersion: v1
  metadata:
    name: "${NAME}"
  stringData:
    redis-password: "${REDIS_PASSWORD}"
    database-user: "${DATABASE_USER}"
    database-password: "${DATABASE_PASSWORD}"
    database-admin-password: "${DATABASE_ADMIN_PASSWORD}"
    application-user: "${APPLICATION_USER}"
    application-password: "${APPLICATION_PASSWORD}"
    keybase: "${SECRET_KEY_BASE}"
- kind: Service
  apiVersion: v1
  metadata:
    name: "${NAME}"
    annotations:
      description: Exposes and load balances the application pods
      service.alpha.openshift.io/dependencies: '[{"name": "${DATABASE_SERVICE_NAME}",
        "kind": "Service"}]'
  spec:
    ports:
    - name: web
      port: 8080
      targetPort: 8080
    selector:
      name: "${NAME}"
- kind: Route
  apiVersion: v1
  metadata:
    name: "${NAME}"
  spec:
    host: "${APPLICATION_DOMAIN}"
    to:
      kind: Service
      name: "${NAME}"
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${NAME}"
    annotations:
      description: Keeps track of changes in the application image
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "${NAME}"
    annotations:
      description: Defines how to build the application
      template.alpha.openshift.io/wait-for-ready: 'true'
  spec:
    source:
      type: Git
      git:
        uri: "${SOURCE_REPOSITORY_URL}"
        ref: "${SOURCE_REPOSITORY_REF}"
      contextDir: "${CONTEXT_DIR}"
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          namespace: "${NAMESPACE}"
          name: ruby:2.4
        env:
        - name: RUBYGEM_MIRROR
          value: "${RUBYGEM_MIRROR}"
    output:
      to:
        kind: ImageStreamTag
        name: "${NAME}:latest"
    triggers:
    - type: ImageChange
    - type: ConfigChange
    - type: GitHub
      github:
        secret: "${GITHUB_WEBHOOK_SECRET}"
    postCommit:
      script: bundle exec rake test
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${NAME}"
    annotations:
      description: Defines how to deploy the application server
      template.alpha.openshift.io/wait-for-ready: 'true'
  spec:
    strategy:
      type: Recreate
      recreateParams:
        pre:
          failurePolicy: Abort
          execNewPod:
            command:
            - "./migrate-database.sh"
            containerName: "${NAME}"
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - "${NAME}"
        from:
          kind: ImageStreamTag
          name: "${NAME}:latest"
    - type: ConfigChange
    replicas: 1
    selector:
      name: "${NAME}"
    template:
      metadata:
        name: "${NAME}"
        labels:
          name: "${NAME}"
      spec:
        containers:
        - name: "${NAME}"
          image: " "
          ports:
          - containerPort: 8080
          readinessProbe:
            timeoutSeconds: 3
            initialDelaySeconds: 5
            httpGet:
              path: "/articles"
              port: 8080
          livenessProbe:
            timeoutSeconds: 3
            initialDelaySeconds: 10
            httpGet:
              path: "/articles"
              port: 8080
          env:
          - name: DATABASE_SERVICE_NAME
            value: "${DATABASE_SERVICE_NAME}"
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                name: "${NAME}"
                key: database-user
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "${NAME}"
                key: database-password
          - name: POSTGRESQL_DATABASE
            value: "${DATABASE_NAME}"
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: "${NAME}"
                key: keybase
          - name: POSTGRESQL_MAX_CONNECTIONS
            value: "${POSTGRESQL_MAX_CONNECTIONS}"
          - name: POSTGRESQL_SHARED_BUFFERS
            value: "${POSTGRESQL_SHARED_BUFFERS}"
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "${NAME}"
                key: redis-password
          - name: APPLICATION_DOMAIN
            value: "${APPLICATION_DOMAIN}"
          - name: APPLICATION_USER
            valueFrom:
              secretKeyRef:
                name: "${NAME}"
                key: application-user
          - name: APPLICATION_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "${NAME}"
                key: application-password
          - name: RAILS_ENV
            value: "${RAILS_ENV}"
          resources:
            limits:
              memory: "${MEMORY_LIMIT}"
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: worker
    annotations:
      description: Defines how to deploy the application server
      template.alpha.openshift.io/wait-for-ready: 'true'
  spec:
    strategy:
      type: Custom
      customParams:
        image: "${NAME}:latest"
        command:
          - bundle
          - exec
          - sidekiq
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - worker
        from:
          kind: ImageStreamTag
          name: "${NAME}:latest"
    - type: ConfigChange
    replicas: 1
    selector:
      name: worker
    template:
      metadata:
        name: worker
        labels:
          name: worker
      spec:
        containers:
        - name: worker
          image: " "
          env:
          - name: DATABASE_SERVICE_NAME
            value: "${DATABASE_SERVICE_NAME}"
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                name: "${NAME}"
                key: database-user
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "${NAME}"
                key: database-password
          - name: POSTGRESQL_DATABASE
            value: "${DATABASE_NAME}"
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: "${NAME}"
                key: keybase
          - name: POSTGRESQL_MAX_CONNECTIONS
            value: "${POSTGRESQL_MAX_CONNECTIONS}"
          - name: POSTGRESQL_SHARED_BUFFERS
            value: "${POSTGRESQL_SHARED_BUFFERS}"
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "${NAME}"
                key: redis-password
          - name: APPLICATION_DOMAIN
            value: "${APPLICATION_DOMAIN}"
          - name: APPLICATION_USER
            valueFrom:
              secretKeyRef:
                name: "${NAME}"
                key: application-user
          - name: APPLICATION_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "${NAME}"
                key: application-password
          - name: RAILS_ENV
            value: "${RAILS_ENV}"
          resources:
            limits:
              memory: "${MEMORY_LIMIT}"
- kind: Service
  apiVersion: v1
  metadata:
    name: "${DATABASE_SERVICE_NAME}"
    annotations:
      description: Exposes the database server
  spec:
    ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
    selector:
      name: "${DATABASE_SERVICE_NAME}"
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${DATABASE_SERVICE_NAME}"
    annotations:
      description: Defines how to deploy the database
      template.alpha.openshift.io/wait-for-ready: 'true'
  spec:
    strategy:
      type: Recreate
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - postgresql
        from:
          kind: ImageStreamTag
          namespace: "${NAMESPACE}"
          name: postgresql:9.5
    - type: ConfigChange
    replicas: 1
    selector:
      name: "${DATABASE_SERVICE_NAME}"
    template:
      metadata:
        name: "${DATABASE_SERVICE_NAME}"
        labels:
          name: "${DATABASE_SERVICE_NAME}"
      spec:
        volumes:
        - name: data
          emptyDir: {}
        containers:
        - name: postgresql
          image: " "
          ports:
          - containerPort: 5432
          readinessProbe:
            timeoutSeconds: 1
            initialDelaySeconds: 5
            exec:
              command:
              - "/usr/libexec/check-container"
          livenessProbe:
            timeoutSeconds: 10
            initialDelaySeconds: 120
            exec:
              command:
              - "/usr/libexec/check-container"
              - "--live"
          volumeMounts:
          - name: data
            mountPath: "/var/lib/pgsql/data"
          env:
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                name: "${NAME}"
                key: database-user
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "${NAME}"
                key: database-password
          - name: POSTGRESQL_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "${NAME}"
                key: database-admin-password
          - name: POSTGRESQL_DATABASE
            value: "${DATABASE_NAME}"
          - name: POSTGRESQL_MAX_CONNECTIONS
            value: "${POSTGRESQL_MAX_CONNECTIONS}"
          - name: POSTGRESQL_SHARED_BUFFERS
            value: "${POSTGRESQL_SHARED_BUFFERS}"
          resources:
            limits:
              memory: "${MEMORY_POSTGRESQL_LIMIT}"
- kind: Service
  apiVersion: v1
  metadata:
    annotations:
      template.openshift.io/expose-uri: redis://{.spec.clusterIP}:{.spec.ports[?(.name=="redis")].port}
    name: "${REDIS_SERVICE_NAME}"
  spec:
    ports:
    - name: redis
      nodePort: 0
      port: 6379
      protocol: TCP
      targetPort: 6379
    selector:
      name: "${REDIS_SERVICE_NAME}"
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: 'true'
    name: "${REDIS_SERVICE_NAME}"
  spec:
    replicas: 1
    selector:
      name: "${REDIS_SERVICE_NAME}"
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: "${REDIS_SERVICE_NAME}"
      spec:
        containers:
        - capabilities: {}
          env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                key: redis-password
                name: "${NAME}"
          image: " "
          imagePullPolicy: IfNotPresent
          livenessProbe:
            initialDelaySeconds: 30
            tcpSocket:
              port: 6379
            timeoutSeconds: 1
          name: redis
          ports:
          - containerPort: 6379
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - "/bin/sh"
              - "-i"
              - "-c"
              - test "$(redis-cli -h 127.0.0.1 -a $REDIS_PASSWORD ping)" == "PONG"
            initialDelaySeconds: 5
            timeoutSeconds: 1
          resources:
            limits:
              memory: "${MEMORY_LIMIT}"
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: "/dev/termination-log"
          volumeMounts:
          - mountPath: "/var/lib/redis/data"
            name: "${REDIS_SERVICE_NAME}-data"
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        volumes:
        - emptyDir:
            medium: ''
          name: "${REDIS_SERVICE_NAME}-data"
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - redis
        from:
          kind: ImageStreamTag
          name: redis:${REDIS_VERSION}
          namespace: openshift
        lastTriggeredImage: ''
      type: ImageChange
    - type: ConfigChange
parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all of the frontend objects defined in this template.
  required: true
  value: web
- name: NAMESPACE
  displayName: Namespace
  required: true
  description: The OpenShift Namespace where the ImageStream resides.
  value: rit-class-stats
- name: MEMORY_LIMIT
  displayName: Memory Limit
  required: true
  description: Maximum amount of memory the Rails container can use.
  value: 512Mi
- name: MEMORY_POSTGRESQL_LIMIT
  displayName: Memory Limit (PostgreSQL)
  required: true
  description: Maximum amount of memory the PostgreSQL container can use.
  value: 512Mi
- name: SOURCE_REPOSITORY_URL
  displayName: Git Repository URL
  required: true
  description: The URL of the repository with your application source code.
  value: https://github.com/openshift/rails-ex.git
- name: SOURCE_REPOSITORY_REF
  displayName: Git Reference
  description: Set this to a branch name, tag or other ref of your repository if you
    are not using the default branch.
- name: CONTEXT_DIR
  displayName: Context Directory
  description: Set this to the relative path to your project if it is not in the root
    of your repository.
- name: APPLICATION_DOMAIN
  displayName: Application Hostname
  description: The exposed hostname that will route to the Rails service, if left
    blank a value will be defaulted.
  value: ''
- name: GITHUB_WEBHOOK_SECRET
  displayName: GitHub Webhook Secret
  description: Github trigger secret.  A difficult to guess string encoded as part
    of the webhook URL.  Not encrypted.
  generate: expression
  from: "[a-zA-Z0-9]{40}"
- name: SECRET_KEY_BASE
  displayName: Secret Key
  description: Your secret key for verifying the integrity of signed cookies.
  generate: expression
  from: "[a-z0-9]{127}"
- name: APPLICATION_USER
  displayName: Application Username
  required: true
  description: The application user that is used within the sample application to
    authorize access on pages.
  value: openshift
- name: APPLICATION_PASSWORD
  displayName: Application Password
  required: true
  description: The application password that is used within the sample application
    to authorize access on pages.
  value: secret
- name: RAILS_ENV
  displayName: Rails Environment
  required: true
  description: Environment under which the sample application will run. Could be set
    to production, development or test.
  value: production
- name: DATABASE_SERVICE_NAME
  required: true
  displayName: Database Service Name
  value: postgresql
- name: DATABASE_USER
  displayName: Database Username
  generate: expression
  from: user[A-Z0-9]{3}
- name: DATABASE_PASSWORD
  displayName: Database Password
  generate: expression
  from: "[a-zA-Z0-9]{8}"
- name: DATABASE_ADMIN_PASSWORD
  displayName: Database Admin Password
  generate: expression
  from: "[a-zA-Z0-9]{8}"
- name: DATABASE_NAME
  required: true
  displayName: Database Name
  value: root
- name: POSTGRESQL_MAX_CONNECTIONS
  displayName: Maximum Database Connections
  value: '100'
- name: POSTGRESQL_SHARED_BUFFERS
  displayName: Shared Buffer Amount
  value: 12MB
- name: RUBYGEM_MIRROR
  displayName: Custom RubyGems Mirror URL
  description: The custom RubyGems mirror URL
  value: ''
- name: REDIS_SERVICE_NAME
  displayName: Redis Service Name
  value: redis
- name: REDIS_PASSWORD
  displayName: Redis Connection Password
  generate: expression
  from: "[a-zA-Z0-9]{16}"
- name: REDIS_VERSION
  displayName: Version of Redis Image
  value: '3.2'
